### ISSUE TITLE
"User testing" the POW! writing up my questions and ideas here more like "unicorn testing" maybe

### ISSUE THREAD

**Issue by olavea** [raae/pow-app#103]
1.
Why is Netlify set to "locked deploy"?
ref: https://app.netlify.com/sites/pow-app/deploys/5e555ae298bf990009fec0d0
***
2.
How do I choose monthly payment? I got here after signing in as "unicorn" 
ref: ["unicorn horn payment" ](https://checkout.stripe.com/pay/ppage_1GICKmHmFMSlODIrCWkMwK1B#fidkdWxOYHwnPyd1blpxYHZxWmFCTjI8b21NYElHaUJ1XH1pVGpAQmpgcjU1Q11xYTBJdncnKSd3YGNgd3dgd0p3bGJsayc%2FJ21xcXV2PyoqMGAwZjUxMzQxPTQxNWE1NTUyZj0wNGcyKCh1anIoZHV1K2tgcWlsY3wrZmpoJyknaWpmZGlgJz9rcGlpKSdobGF2Jz9%2BJ2JwbGEnPydnPDBkMWBmMChjPDFmKDE9YzwoZDY1NygzMzE8PTw8Y2NnYDUnKSdocGxhJz8nZ2RhNTRmPGYoPWQ9PCgxNmY2KD01YTwoZj02MmBjZj03NDJkJykndmxhJz8nZDQzM2A1ZGcoNWM3NCgxPGcyKDw1MmcoPTE1ZjUyNmcyMjQxJ3gpJ2dgcWR2Jz9eWHgl)

Via: 
https://5e5c046148140d0007c851b7--pow-app.netlify.com/payment/?stripe=failed

<img width="1440" alt="POW!-pay-96" src="https://user-images.githubusercontent.com/7642493/75672604-5b44e600-5c81-11ea-9e62-470dd5229f3b.png">

mostly = monthly

Found the answer:
<img width="1440" alt="POW!-pay-100" src="https://user-images.githubusercontent.com/7642493/75675237-10c66800-5c87-11ea-9d35-cd05756fe2fe.png">

***
3. 
How do I log out from the https://www.usepow.app/payment/?stripe=failed page?

4. 
Why beta_is_paused?
<img width="660" alt="POW!-signup_beta_is_paused-98" src="https://user-images.githubusercontent.com/7642493/75673736-ea52fd80-5c83-11ea-9ead-4926437c187d.png">

5.
Why is this smaller?
Where is this in the code? = UserForm.js
I shall try to find it.
<img width="1440" alt="POW!-signup-99" src="https://user-images.githubusercontent.com/7642493/75674141-c17f3800-5c84-11ea-8fd6-e3e4d83ea61c.png">

I tried, but couldn't make the "sign out" become the same size as "go to app"

<img width="1440" alt="POW!-signup-101" src="https://user-images.githubusercontent.com/7642493/75676454-86333800-5c89-11ea-9d66-0fe2f0675c3c.png">

Ideas
Using issues as CMS for my blog?
@jhooks
https://twitter.com/jhooks/status/1232811965916909568

**Comment by raae** [comment]
1. It's locked because people like me who use the app with blockstack still can use it. And also because master is a little unstable.

**Comment by raae** [comment]
4. Beta is pause as I do not want more people in as blockstack users.

**Comment by raae** [comment]
3. You cannot. Fixed rhisnmorning. But not pushed yet. As I said master will be a little unstable the next few days.

**Comment by raae** [comment]
2. You are supposed to be able to choose monthly if you go back and select monthly on the payment screen.

**Comment by olavea** [comment]
5. I think i fixed this, but I have problems seeing if my fix is working

😸

**Comment by raae** [comment]
5. It's a material design issue. I decided to skip fixing this at the momement. It's important that it's a button.

**Comment by olavea** [comment]
5. Yeah, I found this
https://material-ui.com/components/links/

I also decided to skip it LOL
