### ISSUE TITLE
Add email to Userform 

### ISSUE THREAD

**Issue by olavea** [raae/pow-app#109]
See https://github.com/raae/pow-app/pull/105

**Comment by olavea** [comment]
Benedicte @raae sa (ma. 9 mars kl 11:49) :

Og så må det sendes med til stripe i redirecten om det går.

Eller først må den behandles av handle change så den blir med inn i kallet til signUp.

Og så må.den henter fra user og brukes inn i redirect  til stripe.

**Comment by olavea** [comment]
@olavea  asked 
Do you want the email to show up in the stripe checkout like this:

![POW-signup-email_122](https://user-images.githubusercontent.com/7642493/76407405-96cf6680-638b-11ea-9efe-e9ea04f65b8c.jpg)


Benedicte @raae said (we. 11 mars ) :

Yes I do, but that might not be possible without some more serverless functions.

We might have to:

1. Make a stripe customer using a serverless function
2. Then create a payment checkout session with reference to the customer returned in 1
3. Then use stripe.redirectToCheckout with the session id from 2, instead of off all the info, we send now.


This might be a little much right now, so maybe just let them write it in twice.

When implementing updating payment info this has to be in place, so solve it together with that.

**Comment by olavea** [comment]
I will answer Benedicte @raae 's conclusions:

"This might be a little much right now, so maybe just let them write it in twice."
–I agree. But we must do something later, because one customer will write two different emails. I don't know the consequences of that, but I get a bad feeling...


"When implementing updating payment info this has to be in place, so solve it together with that."

–With this you mean we will later be implementing updating payment info and at that point we will solve the sending of the `"email"` prop from `"signup" in UserForm.js` to `stripe.redirectToCheckout`

**Comment by raae** [comment]
Yes, and yes, there are not consequences of two emails. Its actually a good thing, one might want billing email to be different than email for updates/newsletter.
