### ISSUE TITLE
Add/edit entry on new "page"

### ISSUE THREAD

**Issue by raae** [raae/pow-app#115]
I love my little edit widget, but I must let it go.

When selecting to edit/add the user should be sent to "/cycle/:day/edit".

On small devices, the app bar should change (or maybe just covered) to look similar to examples below, while on larger ones it should be more typical with buttons below.

**Comment by raae** [comment]
Twitter examples:

![twitter com_home(iPhone 6_7_8)](https://user-images.githubusercontent.com/478531/76491719-ac499c80-642e-11ea-923b-8ca40ad2c443.png)

![twitter com_home](https://user-images.githubusercontent.com/478531/76491715-abb10600-642e-11ea-9e4b-0b2bad23e391.png)

![twitter com_home (1)](https://user-images.githubusercontent.com/478531/76491706-a784e880-642e-11ea-9952-b4e529617cc7.png)

**Comment by olavea** [comment]
Questions

1.
Do we want a Modal?
https://material-ui.com/components/modal/
***

2.
Do we want a Dialog?
https://material-ui.com/components/dialogs/
***
