### ISSUE TITLE
Stripe + Userbase = New Payment Flow

### ISSUE THREAD

**Issue by raae** [raae/pow-app#117]
Not a priority yet.

I think Userbase is working on something that will do a lot of this for us, so let's wait and see.

**Comment by olavea** [comment]
I asked @userbaseHQ on twitter:

Looking forward to maybe testing out som beta payments integration stuff if you guys feel like it. Smiling cat face with open mouthThumbs up

I am a junior webdev working with 
@raae
  on the #usepowapp 

Enjoy your weekend Smiling face with 😎 

https://twitter.com/UserbaseHQ/status/1233809436461981696

**Comment by olavea** [comment]
stripe-userbase-new-payment-flow-#117

**Comment by olavea** [comment]
Ref: Docs : SDK :[ purchaseSubscription](https://userbase.com/docs/sdk/purchase-subscription/)
`purchaseSubscription` redirects your users to a Stripe Checkout form. To call the `purchaseSubscription` function, you must first do the following:

- [ ] Include the Stripe.js client in your web app.
- [ ] Connect a Stripe account to your Userbase admin account in the Account section in your Admin panel.
- [ ] Create a new test subscription plan in your Stripe dashboard.
- [ ] Set the test subscription plan ID on your app in your Admin panel and enable payments.
- [ ] error handling

**Comment by olavea** [comment]
.default.purchaseSubscription
is not a function #117
c99b50a

![POW-BRANCH_stripe _#117_is_not_a_function_8-230](https://user-images.githubusercontent.com/7642493/82114984-56f87700-9760-11ea-890b-2dbf32a87454.jpg)

**Comment by olavea** [comment]
RequestFailed: OpenDatabase
![POW-BRANCH_stripe _#117_ RequestFailed_OpenDatabase_13-235](https://user-images.githubusercontent.com/7642493/82137975-fd09b700-981c-11ea-86c8-4799fe6edff7.jpg)

**Comment by raae** [comment]
You probably need to update the userbaser package @olavea as this is new functionality.

`yarn upgrade userbase`

**Comment by olavea** [comment]
Hm...

**Comment by raae** [comment]
We need to wait until support for multible subscription, until then use my "good enough" approach. Since we are waiting for this we will not better out own payment solution. As of now cancelled subscriptions will still have access...

**Comment by raae** [comment]
We will have to change our onboarding some, we could maybe start on that work. We are now adding data to the settings database before collecting payments. 

That would not work when moving to Userbase's payment solution. We could save it in local storage until the user is back from the payment redirect.

Or we could just collect payment first and then do the settings part.

A part of this work could also to have look at the onboarding with fresh eyes and do some user testing etc.

Do you want to start this work @olavea.

**Comment by olavea** [comment]
Ref: Docs : SDK :[ purchaseSubscription](https://userbase.com/docs/sdk/purchase-subscription/)
`purchaseSubscription` redirects your users to a Stripe Checkout form. To call the `purchaseSubscription` function, you must first do the following:

- [ ] Include the Stripe.js client in your web app. Does this mean stripe init und zu weiter?
- [ ] How do I see the current paymentForm in localhost?
- [ ] 1. I just put the `...   .purchaseSubscription({...`right into PaymentForm.js?
- [ ] Where do I put `const { subscribe } = useAuthActions()`
- [ ] Connect a Stripe account to your Userbase admin account in the Account section in your Admin panel.
- [ ] Create a new test subscription plan in your Stripe dashboard.
- [ ] Set the test subscription plan ID on your app in your Admin panel and enable payments.
- [ ] error handling

**Comment by olavea** [comment]
It works locally and in netlify preview:
https://github.com/raae/pow-app/pull/232


Screenshots:

![Payment with stripe POW!-stripe-324](https://user-images.githubusercontent.com/7642493/106758828-46f82e80-6632-11eb-9d56-7a732d048e7e.jpg)


![stripe checkout POW!-stripe-325](https://user-images.githubusercontent.com/7642493/106758845-4a8bb580-6632-11eb-8652-58e8e6ad0bf5.png)
