### ISSUE TITLE
Has remember me stopped working?

### ISSUE THREAD

**Issue by raae** [raae/pow-app#126]

**Comment by olavea** [comment]
Well how do I check this?
I will write down some ideas.
👍

**Comment by olavea** [comment]
Ok:
Did a search "Remember me" in my local POW repo

**Comment by olavea** [comment]
```

  const [dontFrog, setFrog] = React.useState("")
  const remember = dontFrog === "rememberMe"

  const errol = remember ? null : "You forgot rememberMe"
  // if (name === "rememberMe") {
  //   value = event.target.checked ? "local" : "session"
  // }
  function handleDontForget(event) {
    setFrog(event.target.value.checked)
  }
```

**Comment by raae** [comment]
I will take a look at this.

**Comment by raae** [comment]
The value should be "local" when signing in with "rememberMe" checked.

I tried a couple of times on my computer and it remembers me even after closing chrome and opening again. But I know on my phone I am often logged out.
