### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by olavea** [raae/pow-app#138]
typo in #Charge #

**Comment by raae** [comment]
Hi:) Just wanted to let you know of a typo on the website, that you maybe cought already (sorry if so): "If you for any reason is not happy I will refund your money within the first 60 days." should be "If for any reason you are not happy, I will refund your money within the first 60 days." (https://usepow.app/signup)

**Comment by raae** [comment]
Good fall warm up to fix these typos @olavea.
