### ISSUE TITLE
Move marketing page to Squarespace

### ISSUE THREAD

**Issue by raae** [raae/pow-app#148]
We should focus on coding the app, not the marketing pages. Also it will make it easier to get help and move along marketing without us being a bottle neck.

To make the switch we need to
- [x] Replicate today's page (ie. the front page)
- [ ] Remove marketing pages, move cycle page to index (#181)
- [ ] Move app to my.usepow.app by configuring Netlify
- [ ] Configure Squarespace as usepow.app

Later we need to add privacy policy, FAQ etc.

**Comment by olavea** [comment]
👁️ 😺 👍

**Comment by olavea** [comment]
- [ ] beta is now in squarespace
Questions ("check" the boxes for yes, leave the boxes open for "no" :
- [ ] I put it in https://lillylabs.squarespace.com/config/pages is that ok?
- [ ] /signup? will that work as a link?
- [ ] mailto://support@usepow.app  will that work as a link?

- [ ] 
- [ ] 
- [ ]

**Comment by raae** [comment]
Should not be a part of Lilly Labs site. 

I will invite you to the one I started. Also no need for the charge pages, those will be part of the app. Only the front page needs to be moved over.

**Comment by raae** [comment]
This is how far I got.

<img width="720" alt="POW_" src="https://user-images.githubusercontent.com/478531/89273437-d307aa00-d63f-11ea-8b18-64eacc138c8f.png">

**Comment by olavea** [comment]
- [ ] beta is now in squarespace
- [ ] support is now in squarespace

Questions ("check" the boxes for yes, leave the boxes open for "no" :

- [ ] so the link for signup should be my.usepow.app/signup? 
- [ ] mailto://support@usepow.app  will that work as a link?

- [ ] 
- [ ] 
- [ ]

**Comment by raae** [comment]
I changed my mind, lets have info on a sign up page in squarespace. Then we can add a "get started" button or something taking them to sign up in the app.

**Comment by olavea** [comment]
Here are some tiny tasks I need help with:
1. <POW! LOGO>
2. "If you do not menstruate, but would like to keep up with POW! sign up for the newsletter."


![POW-BRANCH_Squarespace-272](https://user-images.githubusercontent.com/7642493/90385724-ce051a80-e083-11ea-9432-4cbd91e06e66.jpg)



3. <YES, LET’S DO THIS> button

![POW-BRANCH_Squarespace-273](https://user-images.githubusercontent.com/7642493/90385841-f7be4180-e083-11ea-9065-2a3bfe2370fb.jpg)

4. 
Me and my laptop

<Foto>
![POW-BRANCH_Squarespace-274](https://user-images.githubusercontent.com/7642493/90385914-158ba680-e084-11ea-9fcf-951928c557ea.jpg)

**Comment by raae** [comment]
I will complete this one @olavea
