### ISSUE TITLE
Add edit password functionality

### ISSUE THREAD

**Issue by raae** [raae/pow-app#167]
The user should be able to change their password.

Similar to change username.

**Comment by raae** [comment]
A good one to grab @olavea

**Comment by olavea** [comment]
Should we have a `label` associated with the `name`attribute for better accessibility?

That's what Kent C. Dodds says in this video

like this

```
          <div>
            {/* adding a label - htmlFor="usernameInput" */}
            <label htmlFor="usernameInput">Username:</label>
            <input id="usernameInput" type="text" />
          </div>
```

**Comment by raae** [comment]
I think the text field from material ui adds a label. Inspect the code on the page and see if that is the case.

**Comment by olavea** [comment]
Ok
😸 👍

**Comment by olavea** [comment]
Hey @raae 
this is working in localhost now 😸 
Should I add some error handling?

I found at least these error messages in the userbase docs:

CurrentPasswordMissing
CurrentPasswordIncorrect
PasswordAttemptLimitExceeded
PasswordMustBeString
PasswordCannotBeBlank
PasswordTooShort
PasswordTooLong

https://userbase.com/docs/sdk/update-user/

**Comment by olavea** [comment]
LILLIAN OLA BNEDICTE

**Comment by raae** [comment]
> LILLIAN OLA BNEDICTE

Did a intern (🦄 5,5) join you for this mornings coding session?

**Comment by raae** [comment]
Yes you should probably do some error handling.

**Comment by olavea** [comment]
Supert!
I'll look into it!
😸
