### ISSUE TITLE
Something is up with sessions

### ISSUE THREAD

**Issue by raae** [raae/pow-app#179]
I fixed it so sessions should be 24 * 7 hours long. 

Looking at local state, the session is set to expire at det correct time. But it seems Userbase's response is invalid session.

![CleanShot 2020-09-02 at 10 31 16@2x](https://user-images.githubusercontent.com/478531/91959607-1faad780-ed09-11ea-8257-0e352285965d.png)

![CleanShot 2020-09-02 at 10 41 06@2x](https://user-images.githubusercontent.com/478531/91959640-28031280-ed09-11ea-9ff2-8dde04bf95c3.png)

**Comment by raae** [comment]
Do you have any input on this @encrypted-dev/@j-berman?

**Comment by j-berman** [comment]
Ah! Apologies, this is a bug on our end. Will fix ASAP.

**Comment by j-berman** [comment]
Should be fixed!

**Comment by raae** [comment]
Seems to be working, thanks!
