### ISSUE TITLE
Export feature

### ISSUE THREAD

**Issue by raae** [raae/pow-app#197]
A user should be able to export to analyse themselves, or if they are quitting.

**Comment by raae** [comment]
Also asked for by a cancelled user.

**Comment by raae** [comment]
How I would approach it @olavea:

First task:
- [ ] Make a new card above the danger zone with export text and button
When the user clicks the export button
- [ ] Get all the entries
- [ ] Create .csv file (I will find a library I have used before
- [ ] Trigger download of the file (not sure how this is done)

**Comment by olavea** [comment]
I'll finish up #184 first

**Comment by olavea** [comment]
Changed my mind, I will start on this also. Playing to one of my strengths playfully starting up something new! 😸 👍

**Comment by olavea** [comment]
https://userbase.com/docs/sdk/get-databases/

If getDatabases is 👍  or not, I will work on hoe to make it work 😺

**Comment by raae** [comment]
I gave som comments in the PR, you shall not talk to Userbase the data is already there in `entries`.

Use and follow this to convert the entries into csv: https://www.papaparse.com/docs#json-to-csv.

**Comment by raae** [comment]
The we have to figure out how to trigger a download of this csv as a file...

**Comment by olavea** [comment]
One step in the right direction 😸 
What is next step?

![POW-eport-317](https://user-images.githubusercontent.com/7642493/105019772-c4bf1600-5a46-11eb-8d72-87af21d7b555.jpg)
