### ISSUE TITLE
Better change password form

### ISSUE THREAD

**Issue by raae** [raae/pow-app#254]
The change password from should apply the suggestions in "Use autocomplete attributes" and "Use hidden fields for implicit information" in https://www.chromium.org/developers/design-documents/create-amazing-password-forms.

**Comment by olavea** [comment]
–Use autocomplete attributes
Am I getting closer to something?

your–current-password
your–new-password


![365DaysOfPOWprogramming-day-129-your–current-password_#254_👈😜-#-337](https://user-images.githubusercontent.com/7642493/117531113-3c5a8600-afe1-11eb-942c-1a1f2a93b95e.jpg)
