### ISSUE TITLE
Better initial cycle length input field

### ISSUE THREAD

**Issue by raae** [raae/pow-app#271]
- Should only be possible to select a number between 10 and 60.
- Placeholder value should stay 28, but if the value turns to -1 /1 then it should turn into 27/29 using onChange.
  - This would happen when using the arrows, or up/down keys etc.

**Comment by SaraVieira** [comment]
Yess! Will be the next fix i make 😃

**Comment by SaraVieira** [comment]
Hey

The second is quite simple as in I can make an onFocus that checks this but being able to select numbers is quite more complicated as there is no native way of doing this and its not a mandatory field so the browser won't give you an error.

I made something I would like to talk to you about on Tuesday so we can see how to proceed here.


Here is the PR: https://github.com/raae/pow-app/pull/274/

**Comment by SaraVieira** [comment]
Maybe a good option instead of locking the person would be to disable the next button if the value is invalid 

And set a tooltip explaining why
