### ISSUE TITLE
Incomplete loop

### ISSUE THREAD

**Issue by raae** [raae/pow-app#292]
I managed to get into this loop, will have look at it:

![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMWVlNTg5NjktNjFkYy00ZjVkLWI3MWQtZGI2Y2JkYmRmMWE0IiwiZGVwbG95X2lkIjoiNjBhNzhkNTEwYWVhMWYwMDA4MjE5ZGFhIiwiaWQiOiIxZWMzOTc2My0zOWVkLTRlZjItYmU3YS0zYjVlNGVhM2QyZmMifQ==)

<details><summary>Browser metadata</summary>

```
Path:      /incomplete/
Browser:   Chrome 90.0.4430.212 on Mac OS 10.13.6
Viewport:  1920 x 978 @2x
Language:  en-GB
Cookies:   Enabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-290--pow-app.netlify.app%2Fincomplete%2F&os=OS+X&os_version=High+Sierra&browser=Chrome&browser_version=90.0&resolution=1920x978&speed=1&start=true)

</details>

[Open Deploy Preview](https://deploy-preview-290--pow-app.netlify.app/incomplete/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60a78d510aea1f0008219daa&commentID=60a790cfac7fc1e6596cd3d3&resolution=resolved)

**Comment by SaraVieira** [comment]
closed by #293
