### ISSUE TITLE
Add goal tracking to the export feature

### ISSUE THREAD

**Issue by raae** [raae/pow-app#302]
When the user clicks the export button it should be tracked.

1. Add GATSBY_FATHOM_EXPORT to your .env.development (any value will due)
2. Export FATHOM_EXPORT from `./constants`
2. Import the `trackGoal` function from the `tracking` feature. 
2. Import `FATHOM_EXPORT` from `./constants`
3. When button is clicked call `trackGoal` with `FATHOM_EXPORT` as param
4. Test and make sure the console logs out `Track fathom goal <FATHOM_EXPORT>)`

I will add a real value to Netlify env variables so this will be tracked properly by fathom in production.

**Comment by olavea** [comment]
Question about
5. When button is clicked call trackGoal with FATHOM_EXPORT as param
A. Should `trackGoal` be called after `openSaveFileDialog`? or
B. Should `trackGoal` be called before `openSaveFileDialog`? 

I am currently going with "B", but you're the POW! Queen @raae 👑  so it's your call.

**Comment by raae** [comment]
Let's do before, as if it fails the intent of the user is still to export. Later we can add some error tracking.
