### ISSUE TITLE
Create POW! Angels page with Stripe

### ISSUE THREAD

**Issue by raae** [raae/pow-app#36]
Deadline Wednesday, Nov __th.
More thoughts about POW! Angels can be found in #34.

**To get started:**  
- [x] Clone repository `git clone git@github.com:raae/pow-app.git`
- [x] Create a branch `git checkout -b angels-page-#36` 
- [x] Install packages `yarn install` (not npm)

**The task**  
- [x] Create a page where the user can choose between three different Stripe products (gold, silver, bronze) and pay.

- [x] Create a page in the pages directory, a js page. Not a md page at this point. Do not think about design or copy at this point, the page should look like this:

- [x] lag en knapp, commit og push
- [x] yarn add gatsby-plugin-stripe
- [x] `gatsby-plugin-stripe` into gatsby-config.js
- [x] Find material-ui default button
- [x] success and cancel is http://localhost:8000/success/ http://localhost:8000/cancel/
- [x] Make four buttons
- [x] Red color from material-ui
- [x] Under each other
- [ ] Fix comments in Pull Request #36 
- [x] Define all sku strings and api strings on top of file to make the code easier to read and later easier to change to production values.
  - Example sku `const BRONZE_SKU = "sku_G7M4igcIzjEhU2"` then for onClick `onClick={() => placeOrder(BRONZE_SKU)}`.
  - Example key `const STRIPE_KEY = "pk_test_XiirziufElakjoOpyuyCrPfo"` and `const stripe = window.Stripe(STRIPE_KEY)`.
- [x] Fix window not defined when doing `yarn build`
  - Do this by using useState `const [stripe, setStripe] = useState()` and then setting `setStripe(window.Stripe(STRIPE_KEY))` inside a useEffect(). If you just want to copy something that works I have created a [gist](https://gist.github.com/raae/6998e692ee16265a2dfa45a350b7cb82)
- [x] Use Material UI Cards around the buttons to add info, see bronze example https://codesandbox.io/s/material-demo-e4jc4 (relevant code inside demo.js file).
- [x]  It would be best to not repeat for each but create an AngelCard component that takes props that replace the text in my example.
- [x] Set up another AngelCard instance with only the button and make it work, to try to understand why it worked yesterday. 😸 
- [x] Then set up another AngelCard instance with only the button and make that the BRONZE one
- [x] Make all the props have right content 
- [x] Move all angel.js code into a `AngelCheckout.js` file creating a `AngelCheckout` component. 
  - `AngelPage` should then be like this
```
const AngelsPage = () => {
  return (
    <BrandLayout>
      <AngelsCeckout></AngelsCeckout>
    </BrandLayout>
  )
}
```
- [x] See if you manage to use an array for description, instead of `description1`, `description2`etc.
```
// I have not checked this code, so might small errors, but wanted to give you an idea.

// When using AngelCard
<AngelCard
  description={["Lifetime access to POW! for one person.", "VIP Treatment at the launch party for you and your +1 guest."]}
  // and rest of props
/>

// Then in AngelCard you must use map to render the array
{description.map(item => <li>{item}</li>)}
```
---
props and set

![20191104_103333](https://user-images.githubusercontent.com/478531/68111147-c5759600-feee-11e9-9e7a-4e582f758cc4.jpg)

**Comment by olavea** [comment]
c/components/Settings.js
  27:19  error  React Hook "useStyles" is called conditionally. React Hooks must be called in the exact same order in every component render. Did you accidentally call a React Hook after an early return?  react-hooks/rules-of-hooks

✖ 1 problem (1 error, 0 warnings)


File: src/components/Settings.js

**Comment by raae** [comment]
Take a look at https://github.com/raae/pow-app/issues/38 for the useStyles error.

I would probably start by creating a page with one checkout button (like you have done before), then change it into three buttons.
