### ISSUE TITLE
Call "useStyles" in correct order.

### ISSUE THREAD

**Issue by olavea** [raae/pow-app#38]
I got this ERROR msg:

When trying to yarn develop

src/components/Settings.js
27:19 error React Hook "useStyles" is called conditionally. React Hooks must be called in the exact same order in every component render. Did you accidentally call a React Hook after an early return? react-hooks/rules-of-hooks

✖ 1 problem (1 error, 0 warnings)

File: src/components/Settings.js

**Comment by raae** [comment]
Yes, this is a linting error and should be fixed. But I think if you delete the node_modules package and the package.lock and do `yarn install` you will not get the error as yarn is locked to an older linting package.
