### ISSUE TITLE
Why is unknown pages not redirected to the gatsby 404 page

### ISSUE THREAD

**Issue by raae** [raae/pow-app#51]
I thought it was because the gatsby netlify plugin was not installed, but it is.

Is the custom header settings the problem?

**Comment by raae** [comment]
Up for grabs @olavea

**Comment by olavea** [comment]
404 page
A custom 404 page wasn't detected
no 404.js in pages

![365DaysOfPOWprogramming-day-131-_fix-_404_page #51 (#) _👈😜-#-341](https://user-images.githubusercontent.com/7642493/117769773-6c4d9780-b234-11eb-9b75-f8112f4d37b1.jpg)


I try to make a 404.js in pages and see what happens
😸

**Comment by olavea** [comment]
What kind of styling do you want?
Do you want an image of a kraken that our intern Lillian (6 🦄 ) has drawn?
[https://github.com/raae/nattermob.dev/discussions/3](https://github.com/raae/nattermob.dev/discussions/3)

**Comment by raae** [comment]
See comments on the Pull Request #269
