### ISSUE TITLE
Replace custom POW! Angels code with a service

### ISSUE THREAD

**Issue by raae** [raae/pow-app#83]
I think it stands between Podia and Patreon.

Patreon is very much about rewards, but could of course not promise much at each tire. It is branded Patreon. This could be both seen as good and bad.

Podia is a membership and course platform.

Both will let med do public and Angel only content. However, with Podia, I could also develop small courses and digital downloads only the Angels would get access to. And I think that sort of content could be the reward they get.

**Comment by olavea** [comment]
So why did Swizec make his own course platform if Podia or Patreon is a good long term alternative?
Why are not Scott Tolinski and Wes Bos using them?

**Comment by olavea** [comment]
What is it you want to accomplish really?

What is ___
Doing ___
For the donators.

What is ___
Doing ___
For the "investors".

**Comment by raae** [comment]
Yes, let's focus on the product for now.
