### ISSUE TITLE
Refactor SignInForm to UserForm

### ISSUE THREAD

**Issue by raae** [raae/pow-app#91]
The SignInForm handles signing in new users, refactor it so it also can be used as as signup form.

It is used in `login.mdx`, to be found at http://localhost:8000/login.

- [x] Take the SignInForm and refactor it into UserForm.

- [x] The UserForm should take the props variant, this could be "signup" or "signin". 

**You then need to check if:** 
- [x] variant is "signup" in `handleSubmit` for `signup` and 
- [ ] "signin" in `handleSubmit` for `submit`.

**You should also:** 
- [x] change the bottom text so there is one for "signin" and one for "signup".

When doing this make sure to:
- [x]  fix the use in `Mdx` component as well as 
- [x] its use in "login.mdx". Also 
- [x] create a "signup.mdx" to test the new signup usecase.
 

---
Process:
`git clone git@github.com:raae/pow-app.git` if you have not already
`git checkout userbase` to get to the userbase branch
`git checkout -b signup` to create a branch for this refactor
`yarn install` to make sure all packages are up to date
Create `.env.development` file in root, copy content of `.env.example` and add your own key.
`git commit -a -m <message>` to commit small working changes
`git push` to send to GitHub, then create a pull request towards onboarding

**Comment by olavea** [comment]
I am working on it 😸

**Comment by olavea** [comment]
@raae 
Should we have a:
 <FormControlLabel
... label="Remember me"

If we do not remember their password?
Or do we remember their password?
Or do we keep them logged in?

**Comment by olavea** [comment]
It works on localhost:8000/signup
😸 👍 
So please take a look @raae

**Comment by olavea** [comment]
I now have a signup form. 
Use UserForm as both a signup form and a signin form. 
So we can delete SignInForm.

The way I would like to use it is

- [ ] 

```
<UserForm variant="signup" />
```

and 
- [ ] 
```
<UserForm variant="signin" />
```

Continue with what you have
 make use of the variant prop to decide:
- [ ] if it should do signup or sign in action in handle submit
- [ ] what text "Sign Up" or "Log in" to show on the button
- [ ] what helper text to show below the button

**Comment by olavea** [comment]
const handleSubmit = (event) => {
    event.preventDefault()
    if ((variant = "signUp")) {
      signUp(state)
    } else
      signIn(state).then(() => {
        navigate("/app")
      })
  }

**Comment by olavea** [comment]
```
  const handleSubmit = (event) => {
    event.preventDefault()
    if ((variant = "signUp")) {
      signUp(state)
    } else
      signIn(state).then(() => {
        navigate("/app")
      })
  }
```

**Comment by raae** [comment]
Solve by PL #93 and merge to master with PL #94
